###### Datasets with preprocessing

datasets.allowed=lgeo,pg,swdf,geology,dbp

# File paths of datasets  
datasets.lgeo.filepath=datasets/LinkedGeoGraphs/
datasets.pg.filepath=datasets/PersonGraph/
datasets.swdf.filepath=datasets/SemanticWebDogFood/
datasets.geology.filepath=datasets/GeologyGraphs/
datasets.dbp.filepath=datasets/DBpedia/

###### Metrics
metrics=nodetriangle,edgetriangle,maxindegree,maxoutdegree,stdindegree,stdoutdegree,#edges,#vertices,avgDegree
metrics.store=value_store.val
results.file=output/results.csv

# Refinement operator strategy
refinement.operator=leafNode
